FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow

ENV BACKEND_URI sqlite:///mlflow.db

EXPOSE 5000

CMD ["mlflow", "ui", "--backend-store-uri", "${BACKEND_URI}", "--host", "0.0.0.0"]
